package escalator.db.generators

import java.io.File
import scala.io.Source
import escalator.util.disk.FileUtil

/**
 * Prunes unused auto-generated methods from table files to speed up compilation.
 *
 * For each PostgresXxxTable.scala / XxxTable.scala pair, parses method definitions,
 * searches the project for usages, and comments out unused methods with [PRUNED] markers.
 */
class DbPruner(options: CodegenOptions, customGen: CustomGenerator) {

  val PRUNED_START = "// [PRUNED-START]"
  val PRUNED_END   = "// [PRUNED-END]"
  val PRUNED_TRAIT  = "// [PRUNED]"
  val AUTO_GENERATED_MARKER = GeneratorTemplates.autoGeneratedCommentTracker()

  // Methods that must never be pruned
  val PROTECTED_METHODS: Set[String] = Set(
    "db", "monitored", "tableName"
    // "getById", "getByIds", "update", "upsert", "delete", "count", "getAll","insert"
  )

  // Regex to detect method definitions at class level (1 or 2 leading spaces/tabs)
  val METHOD_DEF_REGEX = """^\s{1,4}(override\s+)?(private\s+)?def\s+(\w+)""".r

  case class MethodInfo(
    name: String,
    startLine: Int,   // 0-indexed
    endLine: Int,     // 0-indexed, inclusive
    isPrivate: Boolean,
    isOverride: Boolean
  )

  case class TableFilePair(
    tableName: String,
    traitFile: String,
    implFile: String,
    repositoryFile: Option[String]
  )

  // ==================== Main Entry Points ====================

  def run(): Unit = {
    println("=" * 60)
    println("dbPrune - Commenting out unused auto-generated methods")
    println("=" * 60)

    val pairs = discoverFilePairs()
    println(s"Found ${pairs.size} auto-generated table file pairs")

    if (pairs.isEmpty) {
      println("No table files found to prune.")
      return
    }

    // Load all project source files into memory for searching
    val searchCorpus = loadSearchCorpus()
    println(s"Loaded ${searchCorpus.size} source files for usage search")
    println()

    var totalPruned = 0
    var totalMethods = 0

    pairs.foreach { pair =>
      val (pruned, total) = pruneTable(pair, searchCorpus)
      totalPruned += pruned
      totalMethods += total
    }

    println()
    println("=" * 60)
    println(s"dbPrune complete: ${totalPruned} methods pruned out of ${totalMethods} total")
    println("=" * 60)
  }

  def unprune(): Unit = {
    println("=" * 60)
    println("dbUnprune - Restoring all pruned methods")
    println("=" * 60)

    val pairs = discoverFilePairs()
    var restoredFiles = 0

    pairs.foreach { pair =>
      val implRestored = unpruneFile(pair.implFile)
      val traitRestored = unpruneFile(pair.traitFile)
      if (implRestored || traitRestored) restoredFiles += 1
    }

    println(s"Restored ${restoredFiles} files")
  }

  // ==================== File Discovery ====================

  private def discoverFilePairs(): List[TableFilePair] = {
    val postgresTablesDir = new File(options.postgresFolder, "tables")
    val databaseTablesDir = new File(options.databaseFolder, "tables")

    if (!postgresTablesDir.exists()) {
      println(s"Warning: postgres tables directory not found: ${postgresTablesDir.getAbsolutePath}")
      return List.empty
    }

    findScalaFiles(postgresTablesDir).flatMap { implFile =>
      val fileName = implFile.getName
      if (fileName.startsWith("Postgres") && fileName.endsWith("Table.scala")) {
        val content = readFile(implFile.getAbsolutePath)
        if (content.contains(AUTO_GENERATED_MARKER)) {
          val baseTableName = fileName.stripPrefix("Postgres").stripSuffix(".scala")
          val traitFileName = baseTableName + ".scala"

          // Determine subdirectory (domain/, platform/, or root)
          val subDir = implFile.getParentFile.getName match {
            case "tables" => ""
            case other    => other
          }

          val traitFile = if (subDir.nonEmpty) {
            new File(new File(databaseTablesDir, subDir), traitFileName)
          } else {
            new File(databaseTablesDir, traitFileName)
          }

          val repoFileName = baseTableName.stripSuffix("Table") + "Repository.scala"
          val repoFile = if (options.repositoriesFolder.nonEmpty) {
            val repoDir = if (subDir.nonEmpty) {
              new File(options.repositoriesFolder, subDir)
            } else {
              new File(options.repositoriesFolder)
            }
            val f = new File(repoDir, repoFileName)
            if (f.exists()) Some(f.getAbsolutePath) else None
          } else None

          if (traitFile.exists()) {
            Some(TableFilePair(
              tableName = baseTableName.stripSuffix("Table"),
              traitFile = traitFile.getAbsolutePath,
              implFile = implFile.getAbsolutePath,
              repositoryFile = repoFile
            ))
          } else {
            println(s"Warning: trait file not found for ${fileName}: ${traitFile.getAbsolutePath}")
            None
          }
        } else None
      } else None
    }
  }

  private def findScalaFiles(dir: File): List[File] = {
    if (!dir.exists()) return List.empty
    val files = dir.listFiles().toList
    val scalaFiles = files.filter(f => f.isFile && f.getName.endsWith(".scala"))
    val subDirFiles = files.filter(_.isDirectory).flatMap(findScalaFiles)
    scalaFiles ++ subDirFiles
  }

  // ==================== Search Corpus ====================

  private def loadSearchCorpus(): Map[String, String] = {
    val modulesDir = new File(options.appFolder, "modules")
    if (!modulesDir.exists()) {
      println(s"Warning: modules directory not found: ${modulesDir.getAbsolutePath}")
      return Map.empty
    }

    findAllScalaSourceFiles(modulesDir)
      .map(f => f.getAbsolutePath -> readFile(f.getAbsolutePath))
      .toMap
  }

  private def findAllScalaSourceFiles(dir: File): List[File] = {
    if (!dir.exists() || !dir.isDirectory) return List.empty
    if (dir.getName == "target") return List.empty

    val files = dir.listFiles().toList
    val scalaFiles = files.filter(f => f.isFile && f.getName.endsWith(".scala"))
    val subDirFiles = files.filter(d => d.isDirectory).flatMap(findAllScalaSourceFiles)
    scalaFiles ++ subDirFiles
  }

  // ==================== Method Parsing ====================

  private def parseMethods(lines: Array[String]): List[MethodInfo] = {
    val methodStarts = scala.collection.mutable.ListBuffer[(Int, String, Boolean, Boolean)]()

    lines.zipWithIndex.foreach { case (line, idx) =>
      METHOD_DEF_REGEX.findFirstMatchIn(line).foreach { m =>
        val isOverride = m.group(1) != null
        val isPrivate = m.group(2) != null
        val name = m.group(3)
        methodStarts += ((idx, name, isPrivate, isOverride))
      }
    }

    if (methodStarts.isEmpty) return List.empty

    val methods = methodStarts.zipWithIndex.map { case ((startLine, name, isPrivate, isOverride), idx) =>
      val endLine = if (idx + 1 < methodStarts.size) {
        // End just before next method, skipping trailing blank lines
        var end = methodStarts(idx + 1)._1 - 1
        while (end > startLine && lines(end).trim.isEmpty) end -= 1
        end
      } else {
        // Last method - ends at the line before the class closing brace
        var end = lines.length - 1
        while (end > startLine && lines(end).trim != "}") end -= 1
        end - 1  // line before closing brace
        // But also skip trailing blank lines
        while (end > startLine && lines(end).trim.isEmpty) end -= 1
        end
      }

      MethodInfo(name, startLine, endLine, isPrivate, isOverride)
    }

    methods.toList
  }

  // ==================== Usage Search ====================

  private def isMethodUsed(
    methodName: String,
    implFile: String,
    implLines: Array[String],
    methods: List[MethodInfo],
    pair: TableFilePair,
    searchCorpus: Map[String, String]
  ): Boolean = {
    // Find all definition lines for this method (could be overloaded)
    val definitionLineIndices = methods.filter(_.name == methodName).flatMap { m =>
      (m.startLine to m.endLine).toSet
    }.toSet

    // 1. Internal usage: method called within the same impl file, outside its own definition
    val internalUsage = implLines.zipWithIndex.exists { case (line, idx) =>
      !definitionLineIndices.contains(idx) && line.contains(methodName)
    }
    if (internalUsage) return true

    // 2. Repository usage
    pair.repositoryFile.foreach { repoPath =>
      searchCorpus.get(repoPath).foreach { content =>
        if (content.contains(methodName)) return true
      }
    }

    // 3. Project-wide usage (exclude the impl file and trait file)
    val excludePaths = Set(implFile, pair.traitFile) ++ pair.repositoryFile.toSet
    searchCorpus.foreach { case (path, content) =>
      if (!excludePaths.contains(path) && content.contains(methodName)) return true
    }

    false
  }

  // ==================== Pruning Logic ====================

  private def pruneTable(pair: TableFilePair, searchCorpus: Map[String, String]): (Int, Int) = {
    val implContent = readFile(pair.implFile)
    val implLines = implContent.split("\n", -1)
    val methods = parseMethods(implLines)

    if (methods.isEmpty) return (0, 0)

    // Get unique method names (handles overloads)
    val uniqueMethodNames = methods.map(_.name).distinct

    // First pass: find methods with no external usage
    val candidatesForPruning = uniqueMethodNames.filter { name =>
      if (PROTECTED_METHODS.contains(name)) {
        false
      } else {
        !isMethodUsed(name, pair.implFile, implLines, methods, pair, searchCorpus)
      }
    }.toSet

    // Second pass: keep private methods that are called by surviving methods
    val methodsToPrune = candidatesForPruning.filter { name =>
      val isPrivate = methods.find(_.name == name).exists(_.isPrivate)
      if (isPrivate) {
        // Check if any non-pruned method calls this private method
        val survivingMethods = methods.filter(m => !candidatesForPruning.contains(m.name))
        val calledBySurvivor = survivingMethods.exists { survivor =>
          (survivor.startLine to survivor.endLine).exists { lineIdx =>
            implLines(lineIdx).contains(name)
          }
        }
        !calledBySurvivor  // prune only if NOT called by a survivor
      } else {
        true  // non-private candidates are always pruned
      }
    }

    if (methodsToPrune.isEmpty) {
      println(s"  ${pair.tableName}: 0/${uniqueMethodNames.size} methods pruned")
      return (0, uniqueMethodNames.size)
    }

    // Apply pruning to impl file
    pruneImplFile(pair.implFile, implLines, methods, methodsToPrune)

    // Apply pruning to trait file
    pruneTraitFile(pair.traitFile, methodsToPrune)

    println(s"  ${pair.tableName}: ${methodsToPrune.size}/${uniqueMethodNames.size} methods pruned")
    (methodsToPrune.size, uniqueMethodNames.size)
  }

  // ==================== Apply Pruning ====================

  private def pruneImplFile(
    filePath: String,
    lines: Array[String],
    methods: List[MethodInfo],
    methodsToPrune: Set[String]
  ): Unit = {
    val result = new StringBuilder()
    val methodsByLine = methods.flatMap { m =>
      (m.startLine to m.endLine).map(lineIdx => lineIdx -> m)
    }.toMap

    // Track which lines are within pruned method blocks
    val prunedLines = methods
      .filter(m => methodsToPrune.contains(m.name))
      .flatMap(m => (m.startLine to m.endLine))
      .toSet

    // Track which methods we've already started pruning (for handling overloads)
    val startedMethods = scala.collection.mutable.Set[Int]()

    var i = 0
    while (i < lines.length) {
      if (prunedLines.contains(i)) {
        // Find the method info for this line
        val method = methodsByLine(i)
        if (!startedMethods.contains(method.startLine)) {
          startedMethods += method.startLine
          // Write pruned block
          result.append(s"${PRUNED_START} ${method.name}\n")
          for (j <- method.startLine to method.endLine) {
            result.append(s"// ${lines(j)}\n")
          }
          result.append(s"${PRUNED_END} ${method.name}\n")
          i = method.endLine + 1
        } else {
          // Already handled by a previous iteration
          i += 1
        }
      } else {
        result.append(lines(i))
        if (i < lines.length - 1) result.append("\n")
        i += 1
      }
    }

    FileUtil.write(filePath, result.toString())
  }

  private def pruneTraitFile(filePath: String, methodsToPrune: Set[String]): Unit = {
    val content = readFile(filePath)
    if (!content.contains(AUTO_GENERATED_MARKER)) return

    val lines = content.split("\n", -1)
    val result = new StringBuilder()
    val traitMethodRegex = """^(\s+)def\s+(\w+)""".r

    var i = 0
    while (i < lines.length) {
      val line = lines(i)
      traitMethodRegex.findFirstMatchIn(line) match {
        case Some(m) if methodsToPrune.contains(m.group(2)) =>
          // Comment out this trait method - may span multiple lines
          // A trait method ends when we hit a line that doesn't continue the signature
          // (i.e., we find the return type closing)
          val methodLines = collectTraitMethodLines(lines, i)
          methodLines.foreach { ml =>
            result.append(s"${PRUNED_TRAIT} ${ml.trim}\n")
          }
          i += methodLines.size
        case _ =>
          result.append(line)
          if (i < lines.length - 1) result.append("\n")
          i += 1
      }
    }

    FileUtil.write(filePath, result.toString())
  }

  private def collectTraitMethodLines(lines: Array[String], startIdx: Int): List[String] = {
    // A trait method definition can span multiple lines.
    // It ends when we see a line ending with a return type (no opening brace).
    // Patterns: "): Future[X]" or "): Future[_]" or single-line "def foo(...): Future[X]"
    val collected = scala.collection.mutable.ListBuffer[String]()
    var i = startIdx
    collected += lines(i)

    // Check if the first line is complete (contains closing paren and return type)
    if (isTraitMethodComplete(lines(i))) {
      return collected.toList
    }

    // Continue collecting lines until we find the closing
    i += 1
    while (i < lines.length) {
      collected += lines(i)
      if (isTraitMethodComplete(lines(i))) {
        return collected.toList
      }
      i += 1
    }

    collected.toList
  }

  private def isTraitMethodComplete(line: String): Boolean = {
    val trimmed = line.trim
    // A trait method signature is complete when it has the return type
    // e.g., ends with "Future[X]" or "Future[_]" or "Boolean" etc.
    // and doesn't end with "=" (which would start an implementation)
    trimmed.contains("): Future[") ||
      trimmed.contains("): Option[") ||
      trimmed.contains("): Boolean") ||
      trimmed.contains("): Long") ||
      trimmed.contains("): Int") ||
      trimmed.contains("): String") ||
      trimmed.contains("): List[") ||
      (trimmed.startsWith("def ") && (
        trimmed.endsWith("]") || trimmed.endsWith(")") || trimmed.endsWith("Boolean") ||
        trimmed.endsWith("Long") || trimmed.endsWith("Int") || trimmed.endsWith("String")
      ))
  }

  // ==================== Unprune ====================

  private def unpruneFile(filePath: String): Boolean = {
    val content = readFile(filePath)
    if (!content.contains(PRUNED_START) && !content.contains(PRUNED_TRAIT)) return false

    val lines = content.split("\n", -1)
    val result = new StringBuilder()
    var inPrunedBlock = false
    var modified = false

    var i = 0
    while (i < lines.length) {
      val line = lines(i)
      if (line.startsWith(PRUNED_START)) {
        inPrunedBlock = true
        modified = true
        i += 1
      } else if (line.startsWith(PRUNED_END)) {
        inPrunedBlock = false
        i += 1
      } else if (inPrunedBlock) {
        // Strip the "// " prefix
        val restored = if (line.startsWith("// ")) line.substring(3) else line
        result.append(restored)
        if (i < lines.length - 1) result.append("\n")
        i += 1
      } else if (line.trim.startsWith(PRUNED_TRAIT.trim)) {
        // Restore trait method
        val restored = line.replace(PRUNED_TRAIT + " ", "  ")
        result.append(restored)
        if (i < lines.length - 1) result.append("\n")
        modified = true
        i += 1
      } else {
        result.append(line)
        if (i < lines.length - 1) result.append("\n")
        i += 1
      }
    }

    if (modified) {
      FileUtil.write(filePath, result.toString())
    }
    modified
  }

  // ==================== Utilities ====================

  private def readFile(path: String): String = {
    val source = Source.fromFile(path)
    try source.mkString
    finally source.close()
  }
}
