package escalator.db.generators

/** CRUD for tables whose identity is supplied by the caller, including composite
  * keys. Never treats the first component of a composite key as the whole key.
  */
object KeyedTableTemplates {
  def applies(t: Table): Boolean = keys(t).size > 1 || !t.hasIdColumn() ||
    (!t.hasColumn("created_at") && !t.hasColumn("updated_at"))

  private def keys(t: Table) = t.tableColumns.filter(c => c.isPrimaryKey && !c.isExtraColumn)
  private def field(c: Column) = GeneratorNamingStrategy.column(c.columnName)
  private def params(t: Table) = keys(t).map(c => c.toArg(GeneratorNamingStrategy,t.name,true)).mkString(", ")
  private def where(t: Table, from: String) = keys(t).map { c =>
    val f=field(c); s"r.$f == lift($from$f)"
  }.mkString(" && ")

  private def unique(t: Table) = t.uniqueKeys.filterNot(_.partial).toList.sortBy(_.keyName).distinctBy(_.cols)
  private def uniqueName(k: UniqueKey) = k.cols.map(c=>GeneratorNamingStrategy.table(c.columnName)).mkString
  private def uniqueColumns(t: Table,k: UniqueKey) = k.cols.map(c=>t.tableColumns.find(_.columnName==c.columnName).get)
  private def uniqueParams(t: Table,k: UniqueKey) = uniqueColumns(t,k).map(_.toArg(GeneratorNamingStrategy,t.name,true)).mkString(", ")
  private def uniqueWhere(t: Table,k: UniqueKey,prefix: String) = uniqueColumns(t,k).map(c=>s"r.${field(c)} == lift($prefix${field(c)})").mkString(" && ")

  def tableTrait(t: Table, pkg: String, model: String, cls: String): String = {
    require(keys(t).nonEmpty,s"Table ${t.name} requires a primary key")
    s"""package $pkg.persistence.database.tables
      |${GeneratorTemplates.autoGeneratedComment}
      |import scala.concurrent.Future
      |import $pkg.models._
      |trait $cls {
      |  def tableName = "${t.name}"
      |  ${unique(t).map(k=>s"def getBy${uniqueName(k)}(${uniqueParams(t,k)}): Future[Option[$model]]\ndef upsertOn${uniqueName(k)}(row: $model): Future[$model]").mkString("\n")}
      |  def getByKey(${params(t)}): Future[Option[$model]]
      |  def insert(row: $model): Future[$model]
      |  def update(row: $model): Future[$model]
      |  def upsert(row: $model): Future[$model]
      |  def delete(row: $model): Future[$model]
      |  def count: Future[Long]
      |  def getAll(): Future[List[$model]]
      |}
      |""".stripMargin
  }

  def dao(t: Table, pkg: String, model: String, cls: String): String = {
    val ks=keys(t)
    val target=ks.map(c=>s"_.${field(c)}").mkString(", ")
    val values=t.tableColumns.filter(c => !c.isPrimaryKey && !c.isExtraColumn)
    val assignments=values.filterNot(_.columnName=="created_at").map(c=>s"(old, incoming) => old.${field(c)} -> incoming.${field(c)}").mkString(", ")
    val keyArgs=ks.map(c=>s"row.${field(c)}").mkString(", ")
    val insert = if (t.hasIdColumn())
      s"ctx.run(querySchema[$model](\"${t.name}\").insert(lift(row)).returningGenerated(_.id)).runToFuture.map(id => row.copy(id=id))"
      else s"ctx.run(querySchema[$model](\"${t.name}\").insert(lift(row))).runToFuture.map(_ => row)"
    val upsert = if (t.hasIdColumn())
      s"if (row.id == ${t.primaryKeyClass().get}(${t.defaultConstructorValue(ks.head)})) insert(row) else update(row)"
      else if (values.nonEmpty)
        s"ctx.run(querySchema[$model](\"${t.name}\").insert(lift(row)).onConflictUpdate($target)($assignments).returning(r => r)).runToFuture"
      else s"ctx.run(querySchema[$model](\"${t.name}\").insert(lift(row)).onConflictIgnore).runToFuture.map(_ => row)"
    val update = if (values.nonEmpty)
      s"ctx.run(querySchema[$model](\"${t.name}\").filter(r => ${where(t,"row.")}).update(lift(row))).runToFuture.flatMap { n => if (n==0) Future.failed(new NoSuchElementException(tableName)) else Future.successful(row) }"
      else s"getByKey($keyArgs).map(_.getOrElse(throw new NoSuchElementException(tableName)))"
    def stamped(body: String, inserting: Boolean): String = {
      val fields=t.tableColumns.filter(c=>c.columnName=="updated_at" || (inserting && c.columnName=="created_at"))
      if(fields.isEmpty) body else {
        val copies=fields.map(c=>s"${field(c)}=${if(c.nullable) "Some(now)" else "now"}").mkString(",")
        val saved=body.replace("lift(row)","lift(persisted)").replace("row.copy(id=id)","persisted.copy(id=id)")
          .replace("map(_ => row)","map(_ => persisted)").replace("Future.successful(row)","Future.successful(persisted)")
        s"{ val now=escalator.util.TimeUtil.nowTimestamp(); val persisted=row.copy($copies); $saved }"
      }
    }
    val insertBody=stamped(insert,true)
    val updateBody=stamped(update,false)
    val upsertBody=if(t.hasIdColumn()) upsert else stamped(upsert,true)
    val uniqueMethods=unique(t).map { key =>
      val name=uniqueName(key)
      val target=uniqueColumns(t,key).map(c=>s"_.${field(c)}").mkString(",")
      val excluded=key.cols.map(_.columnName).toSet++Set("id","created_at")
      val updates=t.tableColumns.filter(c=> !c.isExtraColumn && !excluded(c.columnName))
        .map(c=>s"(old,incoming)=>old.${field(c)} -> incoming.${field(c)}").mkString(",")
      val conflict=if(updates.nonEmpty) s".onConflictUpdate($target)($updates)" else ".onConflictIgnore"
      val returning=if(t.hasIdColumn() && !key.cols.exists(_.columnName=="id")) ".returningGenerated(_.id)" else ""
      val statement=s"ctx.run(querySchema[$model](\"${t.name}\").insert(lift(row))$conflict$returning)"
      val result=s"ctx.run(querySchema[$model](\"${t.name}\").filter(r=>${uniqueWhere(t,key,"row.")}))"
      val body=stamped(s"ctx.transaction { for { _ <- $statement; rows <- $result } yield rows.head }.runToFuture",true)
      s"""override def getBy$name(${uniqueParams(t,key)}): Future[Option[$model]] =
         | ctx.run(querySchema[$model]("${t.name}").filter(r=>${uniqueWhere(t,key,"")})).runToFuture.map(_.headOption)
         |override def upsertOn$name(row: $model): Future[$model] = $body
         |""".stripMargin
    }.mkString("\n")
    s"""package $pkg.persistence.postgres.tables
      |${GeneratorTemplates.autoGeneratedComment}
      |import scala.concurrent.Future
      |import escalator.util.logging.Logger
      |import escalator.util.monitoring.Monitoring
      |import escalator.util.events.EventBus
      |import escalator.util.postgres.PostgresDatabase
      |import $pkg.persistence.postgres.PostgresCustomEncoder
      |import $pkg.common.persistence.postgres.PostgresMappedEncoder
      |import $pkg.models._
      |import $pkg.persistence.database.tables.$cls
      |abstract class Postgres$cls(database: PostgresDatabase)(implicit logger: Logger,
      |    monitoring: Monitoring, eventBus: EventBus) extends $cls with PostgresCustomEncoder {
      |  def db: PostgresDatabase = database
      |  import PostgresMappedEncoder._
      |  import escalator.util.monix.EscalatorScheduler.scheduler
      |  import ctx._
      |  def monitored(name: String) = escalator.util.postgres.MonitoredPostgresOperation(name, tableName)
      |  $uniqueMethods
      |  override def getByKey(${params(t)}): Future[Option[$model]] =
      |    ctx.run(querySchema[$model]("${t.name}").filter(r => ${where(t,"")})).runToFuture.map(_.headOption)
      |  override def insert(row: $model): Future[$model] = $insertBody
      |  override def update(row: $model): Future[$model] = $updateBody
      |  override def upsert(row: $model): Future[$model] = $upsertBody
      |  override def delete(row: $model): Future[$model] =
      |    ctx.run(querySchema[$model]("${t.name}").filter(r => ${where(t,"row.")}).delete).runToFuture.map(_ => row)
      |  override def count: Future[Long] = ctx.run(querySchema[$model]("${t.name}").size).runToFuture
      |  override def getAll(): Future[List[$model]] = ctx.run(querySchema[$model]("${t.name}")).runToFuture
      |}
      |""".stripMargin
  }
}
